#ifndef ALAWWAVEFORMGENERATOR_GLOBAL_H
#define ALAWWAVEFORMGENERATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ALAWWAVEFORMGENERATOR_LIBRARY)
#  define ALAWWAVEFORMGENERATOR_EXPORT Q_DECL_EXPORT
#else
#  define ALAWWAVEFORMGENERATOR_EXPORT Q_DECL_IMPORT
#endif

#endif // ALAWWAVEFORMGENERATOR_GLOBAL_H
